export default {
    sx: 'size',
    w: 'width',
    h: 'height',
    mw: 'maxwidth',
    mh: 'maxheight',
    c: 'crop',
    t: 'thumbnail',
    thumb: 'thumbnail',
    shop: 'shop',
    feed: 'feed',
    wm: 'watermark',
    q: 'quality',
    e: 'extension',
    pk: 'package',
    bd: 'border',
    bg: 'background',
    ty: 'type',
    il: 'imagetopleft',
    ir: 'imagetopright',
    ib: 'imagebottomleft',
    it: 'imagebottomright',
    ic: 'imagecenter',
};